### ISSUE TITLE
Would like to understand better the limitations you encounter with VS Code tasks

### ISSUE THREAD

**Issue by dbaeumer** [guidojo/multipleTypescriptCompilers#1]
Hi,

I am working on VS Code (mainly on tasks) and your tweet got me interested in our project. In general VS Code allows to run multiple tsc compiles in parallel, even in watch mode. So I would like to understand better what limitations you refer to in terms of the problem matcher and whether there is something in VS Code we can do about it. 

One limitation we know is that the output of each run appears in its own terminal so you can't see them all together in one window.

**Comment by guidojo** [comment]
Thank you for your question.

About the vscode part:
This project was created when vscode didn't had the 2.0.0 tasks. After that I tried to configure multiple projects that would run when I start vscode (using the extension Bladerunner or in other words: `ctrl + shift + B`). The only solution I, and other with me, found was using workspaces. This isn't something you'd use in a mono repo (obviously).

The common practise in the Typescript community for mono-repos is to use concurrently, but this only shows the result of the last project when recompiling (which makes sense).

Other benefits:
- Run tslint after project is compiled (tslint doesn't allow watching normally)
- Stop tslint while linting if project is recompiled (don't show lint output in this case)
- Configure tasks with only one line: `mtsc -w -l --noEmit client/special.tsconfig.json server scripts`
- Support build tasks (multiple project outputs with just one command)
- Ability to pass `--noEmit` and `--preserveWatchOutput` to all projects

All in all, the most important thing is to start my favorite IDE, without having to think about tasks. The biggest issue I still have, is that you lose your errors after you close your file. Maybe this isn't an issue for people who use vscode as a better text editor, but it is when you have more than 40 people using vscode to work on some game changing projects. 

I would love to see an example of how you would fix these issues in a mono-repo without my tool, so I might learn something :-)

**Comment by dbaeumer** [comment]
Thanks for the great explanation.

An example how I use task in a mono-repository is here: https://github.com/Microsoft/vscode-languageserver-node

It basically contains 5 npm modules which depend on each other. There are two main composite tasks which run 5 sub tasks for compile and watch. 

I see the advantage of having only one configuration. This is a little harder with plain tsc but can be achieved a little with something like `"extends": "../tsconfig.base.json",` which I use as well.

I have to admit task doesn't offer a good story right now to run dependent tasks on successfull primary task run. Something like run tslint of compile task was successful. But I have feature requests to support this.

Do you have a repository as well were your npm module is used. I am pretty sure I can learn something as well.

**Comment by guidojo** [comment]
Ah thanks, that is a proper example. How does `dependsOn` work? I can't find what `dependsOn` does, it's also not on the [website](https://code.visualstudio.com/docs/editor/tasks-appendix). I really recommend adding some examples about these kind of setups on the vscode website. The documentation isn't really clear about this imo.

I can't give you an example of the projects we have internally, since it's all `proprietary` software, but this is the general structure of a mono repo (ignoring folders that contain docker, Jenkins stuff, etc):
```
* integrationTests
* folderA/client
* folderA/middleware
* scripts/tsscripts
```

Each of them use the same `tslint.json`, but each use a totally different `tsconfig.json`. The client even has multiple; 
* `tsconfig.base.json`
* `tsconfig.json` for vscode that also includes test files
* `webpack.tsconfig.json` webpack that only follows `index.tsx` and ignores other files (like test files)

This is only one of the repositories we have and we have two other big ones that also use Typescript. The only thing you might want to configure in your `tasks.json` is if it needs to watch and `--noEmit`. No emit is nice, because you then don't need multiple tsconfigs if something like webpack is responsible for the output.

Btw, a tsc task doesn't need to be successful to run tslint. The nice thing actually is, that it terminates if that tsc task is done.

**Comment by dbaeumer** [comment]
Thanks for the example. From what I see it is not so different than the https://github.com/Microsoft/vscode-languageserver-node

Short explanation: 'dependsOn' works like a depends clause in normal task runners like gulp. So a task is finished if all tasks it 'dependsOn' are finished and the dependent tasks are executed in parallel.

I fully agree on the documentation part. Created https://github.com/Microsoft/vscode-docs/issues/1528

To my defense the feature is relatively new and I still know things that needs to be improved to make it round. Especially around dependsOn and watching tasks.

**Comment by guidojo** [comment]
Well thank you for this response. I will revise my tool because of this :) If I've found a proper setup that supports everything I want, I'll maybe even completely remove this tool!

No grudge to you or any of the vscode members for not having the proper documentation. We're all on the same team here, trying to get the best dev experience that lets us achieve our goals. If you require any input or feedback about vscode, please let me know. Closing this issue now and will follow the documentation issue.
